services:
  mongodb:
    image: mongo:latest
    command: ['--replSet', 'rs0', '--bind_ip_all']
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongodb
    restart: on-failure
    command: >
      mongosh --host mongodb:27017 --eval '
      rs.initiate({
        _id: "rs0",
        members: [{ _id: 0, host: "localhost:27017" }]
      })
      '

volumes:
  mongodb_data:
