# order-service
services:
  order-service:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
      - '9230:9229'
    volumes:
      - .:/usr/src/app
      - order_service_modules:/usr/src/app/node_modules
    command: yarn start:debug
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3001
    networks:
      - message_broker_network

volumes:
  order_service_modules:

networks:
  message_broker_network:
    external: true
