services:
  order-service:
    build:
      context: .
      target: development # Use development stage from multi-stage Dockerfile
    ports:
      - '3001:3001' # API port
      - '9230:9229' # Map container's 9229 to host's 9230 for debugging
    volumes:
      - .:/usr/src/app # Mount source code for hot reloading
      - /usr/src/app/node_modules # Prevent mounting local node_modules
    command: yarn start:debug # Override CMD from Dockerfile for debugging
    environment:
      - DATABASE_URL=${DATABASE_URL} # MongoDB Atlas connection string
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_INVENTORY_QUEUE=inventory_queue
      - PORT=3001
    networks:
      - message_broker_network # Connect to shared RabbitMQ network

networks:
  message_broker_network:
    external: true # Use pre-existing network from infrastructure
